### ISSUE TITLE
Git , Maven ,NPM , Ansible and Docker Integration with Jenkins

### ISSUE THREAD

**Issue by anandreddyr11** [anand71aws/DevOps#4]
Task:
- [x]  `Create a new Instance from AWS ` --Vidya , Rajesh 
- [x]  `Installation of Pre-Required Software's [Git , Maven ,NPM , Ansible ,Jenkins and Ansible ]   --Anand , Vidya , Rajesh 
- [x]  `Integrate all the Software's through the Jenkins` --Anand ,Vidya
- [x]  `Test with one Java and NodeJS Project with that setup ` --Anand 

Steps:
1. yum update -y
2. yum install wget git unzip zip python php java-1.8.0-openjdk-devel -y
3. Download and Install pre required files [ Maven ,Tomcat , Jenkins , Docker ]
4. Install Docker on Cent os [https://tecadmin.net/install-and-manage-docker-on-centos/]
5. NPM Install [https://www.e2enetworks.com/help/knowledge-base/how-to-install-node-js-and-npm-on-centos/ ]
6. Tested Java Program with jenkins [http://34.246.147.26:8080/jenkins/ ]

**Comment by RajeshBabum1992** [comment]
Npm means

**Comment by anand71aws** [comment]
NPM is the one type of build tool for nodejs.
